#!/usr/bin/env groovy

pipeline {
    agent any
    environment {
        COUNT =  "${params.COUNT_NODES}"
        DRIVER_HOST = "${params.DRIVER_HOST}"
    }
    stages {
       stage('Build and run selenium pytest') {
          steps{
              script {
                  currentBuild.displayName = "Build_Name_count_nodes_$COUNT"
                  currentBuild.description = "Build run with $COUNT threads test to $DRIVER_HOST grid."
                  dir("${env.WORKSPACE}/06-run-selenium-test"){
                    sh "docker build -t selenium_tests ."
                    sh "docker run -v -e DRIVER_HOST=${DRIVER_HOST} -ti selenium_tests pytest -v -n ${COUNT} --html=reports/report.html" 
             }  
            }
          }
       }
    }
}


