#!/usr/bin/env groovy

pipeline {
    agent any
    environment {
        COUNT =  "${params.COUNT_NODES}"
    }
    stages {
       stage('Test') {
          steps{
              script {
                  dir("${env.WORKSPACE}/03-scripts"){
                    sh "ls -l"
                    sh "docker build -t run_containers ."
                    sh "docker run -v /var/run/docker.sock:/var/run/docker.sock -e COUNT=$COUNT run_containers"
             }  
            }
          }
       }
    }
}